In [92]:
from fastai.vision.all import *
# from sklearn.metrics import roc_curve, auc
# from fastai.metrics import * 

# from pathlib import Path
from sklearn.model_selection import   RepeatedKFold, GroupKFold, GroupShuffleSplit, StratifiedGroupKFold, LeaveOneGroupOut, LeavePGroupsOut
from sklearn.utils import resample
import sklearn.metrics as skm
from pathlib import Path
import numpy as np
from numpy import random
import shutil
import glob
import os
import pandas as pd
path = Path('/ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6')

In [93]:
?GroupShuffleSplit

Init signature:
GroupShuffleSplit(
    n_splits=5,
    *,
    test_size=None,
    train_size=None,
    random_state=None,
)
Docstring:
Shuffle-Group(s)-Out cross-validation iterator

Provides randomized train/test indices to split data according to a
third-party provided group. This group information can be used to encode
arbitrary domain specific stratifications of the samples as integers.

For instance the groups could be the year of collection of the samples
and thus allow for cross-validation against time-based splits.

The difference between LeavePGroupsOut and GroupShuffleSplit is that
the former generates splits using all subsets of size ``p`` unique groups,
whereas GroupShuffleSplit generates a user-determined number of random
test splits, each with a user-determined fraction of unique groups.

For example, a less computationally intensive alternative to
``LeavePGroupsOut(p=10)`` would be
``GroupShuffleSplit(test_size=10, n_splits=100)``.

Note: The parameters ``test_size`` and ``train_size`` refer to groups, and
not to samples, as in ShuffleSplit.

Read more in the :ref:`User Guide <group_shuffle_split>`.

Parameters
----------
n_splits : int, default=5
    Number of re-shuffling & splitting iterations.

test_size : float, int, default=0.2
    If float, should be between 0.0 and 1.0 and represent the proportion
    of groups to include in the test split (rounded up). If int,
    represents the absolute number of test groups. If None, the value is
    set to the complement of the train size.
    The default will change in version 0.21. It will remain 0.2 only
    if ``train_size`` is unspecified, otherwise it will complement
    the specified ``train_size``.

train_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the
    proportion of the groups to include in the train split. If
    int, represents the absolute number of train groups. If None,
    the value is automatically set to the complement of the test size.

random_state : int, RandomState instance or None, default=None
    Controls the randomness of the training and testing indices produced.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import GroupShuffleSplit
>>> X = np.ones(shape=(8, 2))
>>> y = np.ones(shape=(8, 1))
>>> groups = np.array([1, 1, 2, 2, 2, 3, 3, 3])
>>> print(groups.shape)
(8,)
>>> gss = GroupShuffleSplit(n_splits=2, train_size=.7, random_state=42)
>>> gss.get_n_splits()
2
>>> for train_idx, test_idx in gss.split(X, y, groups):
...     print("TRAIN:", train_idx, "TEST:", test_idx)
TRAIN: [2 3 4 5 6 7] TEST: [0 1]
TRAIN: [0 1 5 6 7] TEST: [2 3 4]
File:           ~/envs/fastai/lib/python3.8/site-packages/sklearn/model_selection/_split.py
Type:           ABCMeta
Subclasses:

In [5]:
# Create some regular expression queries:
use = 'tiles'
re_class= r"class_(.+)_x\d+_y\d+.jpg"
re_slide =r'(.+)_class_\S+_x\d+_y\d+.jpg$'
re_slide_class=r'(.+)_class_(.+)_x\d+_y\d+.jpg$'
slides=[]
slides_c=[]
all_c=[]
all_f=[]
for f in (path/use).ls():
    all_f.append(f.name)
    slide, c = re.findall(re_slide_class,f.name)[0]
    slides_c.append("%s_%s" % (slide,c))
    slides.append(slide)
    all_c.append(c)
print(np.unique(slides_c), len(np.unique(slides_c)))
posf = np.array([(f,c,s) for f,c,s in zip(all_f,all_c,slides) if c =='pos'])
negf = np.array([(f,c,s) for f,c,s in zip(all_f,all_c,slides) if c =='neg'])
all_dat=pd.DataFrame(all_f,columns=['fn'])
all_dat['slide']=slides
all_dat['class']=all_c
print(all_dat.shape)
u_slides_c=np.unique(slides_c)
temp = [item.split('_') for item in u_slides_c]
slide_df=pd.DataFrame(temp,columns=['slide','group'])
slide_df['class']=slide_df.loc[:,'group']=='pos'

['1007466_neg' '1007467_neg' '1007468_neg' '1007469_neg' '1007470_neg'
 '1007471_neg' '1007473_neg' '1007474_neg' '1007476_pos' '1007477_pos'
 '1007478_pos' '1007482_pos' '1007484_pos' '1007485_pos' '1007486_pos'
 '1007720_neg' '1007726_neg' '1007731_pos' '1007733_pos' '1007820_neg'
 '1007821_neg' '1007822_neg' '1007824_neg' '1007825_neg' '1007826_pos'
 '1007827_pos' '1007828_pos' '1007829_pos' '1007830_pos' '1007831_pos'
 '1007832_pos' '1007845_neg' '1007846_neg' '1007847_neg' '1007848_neg'] 35
(51813, 3)

In [7]:
#Example of Leave-One-Out cross-validation:
u_slides_c=np.unique(slides_c)
temp = [item.split('_') for item in u_slides_c]
slide_df=pd.DataFrame(temp,columns=['slide','group'])
slide_df['class']=slide_df.loc[:,'group']=='pos'
logo=LeaveOneGroupOut()
fold = 0 
    
for slide_train_idx, slide_test_idx in logo.split(slide_df.loc[:,'slide'],
                            slide_df.loc[:,'group'],                                         
                            groups=slide_df.loc[:,'slide']):
    print('\nFold %d' % fold)
    print(len(slide_train_idx),len(slide_test_idx))
    fold += 1

Fold 0
34 1

Fold 1
34 1

Fold 2
34 1

Fold 3
34 1

Fold 4
34 1

Fold 5
34 1

Fold 6
34 1

Fold 7
34 1

Fold 8
34 1

Fold 9
34 1

Fold 10
34 1

Fold 11
34 1

Fold 12
34 1

Fold 13
34 1

Fold 14
34 1

Fold 15
34 1

Fold 16
34 1

Fold 17
34 1

Fold 18
34 1

Fold 19
34 1

Fold 20
34 1

Fold 21
34 1

Fold 22
34 1

Fold 23
34 1

Fold 24
34 1

Fold 25
34 1

Fold 26
34 1

Fold 27
34 1

Fold 28
34 1

Fold 29
34 1

Fold 30
34 1

Fold 31
34 1

Fold 32
34 1

Fold 33
34 1

Fold 34
34 1

# Debug Leave-one-out jack-knife

In [8]:
#Debug leave-one-out jack-knife
seed=42
run_name='resnet18_jackknife'

balance_slides=[False,False]
balance_total_tiles=[True, False] #Train, Test
fold=0
model_path = '%s_model' % use
export_path=path.joinpath(model_path).joinpath(run_name+'/fold_models')
if export_path.exists()==False:
    os.makedirs(export_path)
csv_path=path.joinpath(model_path).joinpath(run_name+'/csv')
if csv_path.exists()==False:
    os.makedirs(csv_path)
    
logo=LeaveOneGroupOut()
for slide_train_idx, slide_test_idx in logo.split(slide_df.loc[:,'slide'],
                            slide_df.loc[:,'group'],                                         
                            groups=slide_df.loc[:,'slide']):
    print('\nFold %d' % fold)
    sets=[slide_train_idx,slide_test_idx]
    set_lab=['train','valid']
    df_list=[]
    n_train_test = [np.sum(slide_df.loc[slide_train_idx,'class']==True), #n pos
                    np.sum(slide_df.loc[slide_train_idx,'class']==False), #n neg
                    np.sum(slide_df.loc[slide_test_idx,'class']==True), #n pos
                    np.sum(slide_df.loc[slide_test_idx,'class']==False)] #n neg
    print('Train slides n=%d pos, %d neg, Test slides n=%d pos, %d neg' % tuple(n_train_test))
    for i,ds in enumerate(sets):   
        use_slides=list(slide_df.loc[ds,'slide'])
        use_tiles=all_dat.loc[:,'slide'].isin(use_slides) #Index of tiles from slide(s) in set (train / valid)
        #balance slides (?):
        #balance per-slide tile (?):
        
        bal_dat=pd.DataFrame(all_dat.loc[use_tiles,('fn','slide','class')]).reset_index(drop=True)
        
        if balance_total_tiles[i] == True:
            #Resample tiles to have equal number of class examples following previous balancing:        
            
            use_fn=bal_dat.loc[use_tiles,'fn']
            use_class=bal_dat.loc[use_tiles,'class']=='pos'
            npos=np.sum(use_class)
            nneg=len(use_class)-npos
            use_n = np.min([npos,nneg])
            print('Balancing %s tiles... %d neg %d pos, use %d' % (set_lab[i],nneg, npos,use_n))
            if npos > nneg:
                old_pos=np.argwhere(np.array(use_class)==True)
                neg=np.argwhere(np.array(use_class)==False)
                new=resample(old_pos,
                             replace=False,
                             n_samples=use_n,
                             random_state=seed)
                bal_tiles_idx=np.concatenate((neg,new))
            elif nneg > npos:
                old_neg=np.argwhere(np.array(use_class)==True)
                pos=np.argwhere(np.array(use_class)==False)
                new=resample(old_neg,
                             replace=False,
                             n_samples=use_n,
                             random_state=seed)
                bal_tiles_idx=np.concatenate((new,pos))
            temp=pd.DataFrame(bal_dat.loc[bal_tiles_idx[:,0],('fn','slide','class')]).reset_index(drop=True)
        else:
            use_class=bal_dat.loc[:,'class']=='pos'
            npos=np.sum(use_class)
            nneg=len(use_class)-npos
            print('Not balancing %s ... %d neg %d pos, use all.' % (set_lab[i],nneg, npos))
            temp=pd.DataFrame(bal_dat.loc[:,('fn','slide','class')]).reset_index(drop=True)
        temp['is_valid']=i
        if i == 0:
            out=temp
        else:
            out=pd.concat((out,temp),axis=0)
    
    full_path_fn=[path.joinpath(use).joinpath(fn) for fn in out['fn']]
    out['full_path']=full_path_fn
    print('Save to %s' % csv_path.joinpath('train_valid_fold_%d.csv' % fold))
    out.to_csv(csv_path.joinpath('train_valid_fold_%d.csv' % fold))
    fold+=1

Fold 0
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 15955 neg 34238 pos, use 15955
Not balancing valid ... 815 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_0.csv

Fold 1
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 16086 neg 34306 pos, use 16086
Not balancing valid ... 714 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_1.csv

Fold 2
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 14705 neg 33574 pos, use 14705
Not balancing valid ... 1794 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_2.csv

Fold 3
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 16221 neg 34381 pos, use 16221
Not balancing valid ... 610 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_3.csv

Fold 4
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 16300 neg 34417 pos, use 16300
Not balancing valid ... 552 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_4.csv

Fold 5
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 16994 neg 34755 pos, use 16994
Not balancing valid ... 32 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_5.csv

Fold 6
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 15523 neg 34006 pos, use 15523
Not balancing valid ... 1152 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_6.csv

Fold 7
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 16232 neg 34348 pos, use 16232
Not balancing valid ... 620 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_7.csv

Fold 8
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 15916 neg 29314 pos, use 15916
Not balancing valid ... 0 neg 3409 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_8.csv

Fold 9
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16810 neg 33714 pos, use 16810
Not balancing valid ... 0 neg 650 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_9.csv

Fold 10
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16641 neg 32810 pos, use 16641
Not balancing valid ... 0 neg 1196 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_10.csv

Fold 11
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 13192 neg 17846 pos, use 13192
Not balancing valid ... 0 neg 11736 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_11.csv

Fold 12
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16803 neg 33650 pos, use 16803
Not balancing valid ... 0 neg 686 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_12.csv

Fold 13
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16952 neg 34402 pos, use 16952
Not balancing valid ... 0 neg 230 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_13.csv

Fold 14
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16423 neg 31792 pos, use 16423
Not balancing valid ... 0 neg 1836 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_14.csv

Fold 15
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 16623 neg 34565 pos, use 16623
Not balancing valid ... 313 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_15.csv

Fold 16
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 16993 neg 34760 pos, use 16993
Not balancing valid ... 30 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_16.csv

Fold 17
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16616 neg 32523 pos, use 16616
Not balancing valid ... 0 neg 1359 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_17.csv

Fold 18
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 15840 neg 29171 pos, use 15840
Not balancing valid ... 0 neg 3520 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_18.csv

Fold 19
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 16663 neg 34608 pos, use 16663
Not balancing valid ... 271 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_19.csv

Fold 20
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 15874 neg 34188 pos, use 15874
Not balancing valid ... 882 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_20.csv

Fold 21
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 15713 neg 34120 pos, use 15713
Not balancing valid ... 996 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_21.csv

Fold 22
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 16782 neg 34658 pos, use 16782
Not balancing valid ... 187 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_22.csv

Fold 23
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 15078 neg 33782 pos, use 15078
Not balancing valid ... 1497 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_23.csv

Fold 24
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16867 neg 33896 pos, use 16867
Not balancing valid ... 0 neg 528 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_24.csv

Fold 25
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16778 neg 33512 pos, use 16778
Not balancing valid ... 0 neg 766 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_25.csv

Fold 26
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16057 neg 29819 pos, use 16057
Not balancing valid ... 0 neg 3056 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_26.csv

Fold 27
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16500 neg 31993 pos, use 16500
Not balancing valid ... 0 neg 1688 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_27.csv

Fold 28
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16507 neg 32373 pos, use 16507
Not balancing valid ... 0 neg 1486 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_28.csv

Fold 29
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16341 neg 31255 pos, use 16341
Not balancing valid ... 0 neg 2149 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_29.csv

Fold 30
Train slides n=15 pos, 19 neg, Test slides n=1 pos, 0 neg
Balancing train tiles... 16857 neg 33988 pos, use 16857
Not balancing valid ... 0 neg 487 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_30.csv

Fold 31
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 16094 neg 34268 pos, use 16094
Not balancing valid ... 731 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_31.csv

Fold 32
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 15697 neg 34119 pos, use 15697
Not balancing valid ... 1010 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_32.csv

Fold 33
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 13259 neg 32856 pos, use 13259
Not balancing valid ... 2942 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_33.csv

Fold 34
Train slides n=16 pos, 18 neg, Test slides n=0 pos, 1 neg
Balancing train tiles... 14598 neg 33519 pos, use 14598
Not balancing valid ... 1883 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v6/tiles_model/resnet18_jackknife/csv/train_valid_fold_34.csv

# Debug 10-fold valid

In [28]:
#Debug 10k-fold``
seed=10
run_name='resnet18_true_10kfold'
u_slides_c=np.unique(slides_c)
temp = [item.split('_') for item in u_slides_c]
slide_df=pd.DataFrame(temp,columns=['slide','group'])
slide_df['class']=slide_df.loc[:,'group']=='pos'
gkf=GroupKFold(n_splits=10)
gkf.get_n_splits(slide_df.loc[:,'slide'],
                            slide_df.loc[:,'group'],
                            groups=slide_df.loc[:,'slide'])
balance_slides=[False,False]
balance_total_tiles=[True, False] #Train, Test
fold=0
model_path = '%s_model' % use
export_path=path.joinpath(model_path).joinpath(run_name+'/fold_models')
if export_path.exists()==False:
    os.makedirs(export_path)
csv_path=path.joinpath(model_path).joinpath(run_name+'/csv')
if csv_path.exists()==False:
    os.makedirs(csv_path)
    
for slide_train_idx, slide_test_idx in gkf.split(slide_df.loc[:,'slide'],
                            slide_df.loc[:,'group'],                                         
                            groups=slide_df.loc[:,'slide']):
    print('\nFold %d' % fold)
    sets=[slide_train_idx,slide_test_idx]
    set_lab=['train','valid']
    df_list=[]
    n_train_test = [np.sum(slide_df.loc[slide_train_idx,'class']==True), #n pos
                    np.sum(slide_df.loc[slide_train_idx,'class']==False), #n neg
                    np.sum(slide_df.loc[slide_test_idx,'class']==True), #n pos
                    np.sum(slide_df.loc[slide_test_idx,'class']==False)] #n neg
    print('Train slides n=%d pos, %d neg, Test slides n=%d pos, %d neg' % tuple(n_train_test))
    for i,ds in enumerate(sets):   
        use_slides=list(slide_df.loc[ds,'slide'])
        use_tiles=all_dat.loc[:,'slide'].isin(use_slides) #Index of tiles from slide(s) in set (train / valid)
        #balance slides (?):
        #balance per-slide tile (?):
        
        bal_dat=pd.DataFrame(all_dat.loc[use_tiles,('fn','slide','class')]).reset_index(drop=True)
        
        if balance_total_tiles[i] == True:
            #Resample tiles to have equal number of class examples following previous balancing:        
            
            use_fn=bal_dat.loc[use_tiles,'fn']
            use_class=bal_dat.loc[use_tiles,'class']=='pos'
            npos=np.sum(use_class)
            nneg=len(use_class)-npos
            use_n = np.min([npos,nneg])
            print('Balancing %s tiles... %d neg %d pos, use %d' % (set_lab[i],nneg, npos,use_n))
            if npos > nneg:
                old_pos=np.argwhere(np.array(use_class)==True)
                neg=np.argwhere(np.array(use_class)==False)
                new=resample(old_pos,
                             replace=False,
                             n_samples=use_n,
                             random_state=seed)
                bal_tiles_idx=np.concatenate((neg,new))
            elif nneg > npos:
                old_neg=np.argwhere(np.array(use_class)==True)
                pos=np.argwhere(np.array(use_class)==False)
                new=resample(old_neg,
                             replace=False,
                             n_samples=use_n,
                             random_state=seed)
                bal_tiles_idx=np.concatenate((new,pos))
            temp=pd.DataFrame(bal_dat.loc[bal_tiles_idx[:,0],('fn','slide','class')]).reset_index(drop=True)
        else:
            use_class=bal_dat.loc[:,'class']=='pos'
            npos=np.sum(use_class)
            nneg=len(use_class)-npos
            print('Not balancing %s ... %d neg %d pos, use all.' % (set_lab[i],nneg, npos))
            temp=pd.DataFrame(bal_dat.loc[:,('fn','slide','class')]).reset_index(drop=True)
        temp['is_valid']=i
        if i == 0:
            out=temp
        else:
            out=pd.concat((out,temp),axis=0)
    
    full_path_fn=[path.joinpath(use).joinpath(fn) for fn in out['fn']]
    out['full_path']=full_path_fn
    print('Save to %s' % csv_path.joinpath('train_valid_fold_%d.csv' % fold))
    out.to_csv(csv_path.joinpath('train_valid_fold_%d.csv' % fold))
    fold+=1

Fold 0
Train slides n=16 pos, 15 neg, Test slides n=0 pos, 4 neg
Balancing train tiles... 3568 neg 9339 pos, use 3568
Not balancing valid ... 1252 neg 0 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v5/tiles_model/resnet18_true_10kfold/csv/train_valid_fold_0.csv

Fold 1
Train slides n=15 pos, 16 neg, Test slides n=1 pos, 3 neg
Balancing train tiles... 4100 neg 8282 pos, use 4100
Not balancing valid ... 600 neg 933 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v5/tiles_model/resnet18_true_10kfold/csv/train_valid_fold_1.csv

Fold 2
Train slides n=14 pos, 17 neg, Test slides n=2 pos, 2 neg
Balancing train tiles... 4334 neg 8750 pos, use 4334
Not balancing valid ... 470 neg 681 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v5/tiles_model/resnet18_true_10kfold/csv/train_valid_fold_2.csv

Fold 3
Train slides n=14 pos, 17 neg, Test slides n=2 pos, 2 neg
Balancing train tiles... 4476 neg 8537 pos, use 4476
Not balancing valid ... 275 neg 927 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v5/tiles_model/resnet18_true_10kfold/csv/train_valid_fold_3.csv

Fold 4
Train slides n=14 pos, 17 neg, Test slides n=2 pos, 2 neg
Balancing train tiles... 3997 neg 8570 pos, use 3997
Not balancing valid ... 754 neg 681 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v5/tiles_model/resnet18_true_10kfold/csv/train_valid_fold_4.csv

Fold 5
Train slides n=14 pos, 18 neg, Test slides n=2 pos, 1 neg
Balancing train tiles... 3676 neg 4923 pos, use 3676
Not balancing valid ... 229 neg 3617 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v5/tiles_model/resnet18_true_10kfold/csv/train_valid_fold_5.csv

Fold 6
Train slides n=14 pos, 18 neg, Test slides n=2 pos, 1 neg
Balancing train tiles... 4829 neg 9148 pos, use 4829
Not balancing valid ... 101 neg 575 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v5/tiles_model/resnet18_true_10kfold/csv/train_valid_fold_6.csv

Fold 7
Train slides n=13 pos, 19 neg, Test slides n=3 pos, 0 neg
Balancing train tiles... 4639 neg 7685 pos, use 4639
Not balancing valid ... 0 neg 1577 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v5/tiles_model/resnet18_true_10kfold/csv/train_valid_fold_7.csv

Fold 8
Train slides n=15 pos, 17 neg, Test slides n=1 pos, 2 neg
Balancing train tiles... 3816 neg 9195 pos, use 3816
Not balancing valid ... 1046 neg 149 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v5/tiles_model/resnet18_true_10kfold/csv/train_valid_fold_8.csv

Fold 9
Train slides n=15 pos, 17 neg, Test slides n=1 pos, 2 neg
Balancing train tiles... 4309 neg 8262 pos, use 4309
Not balancing valid ... 434 neg 1005 pos, use all.
Save to /ix/rbao/Projects/HCC-CBS-068-Hillman-ASinghi-2/data/biliseq_he_class/proc/v5/tiles_model/resnet18_true_10kfold/csv/train_valid_fold_9.csv

In [127]:
#Constrain GroupShuffleSplit so that there are only splits with equal n in classes for train:
k=2
splitter = GroupShuffleSplit(n_splits=1000, 
                             train_size=k,
                             random_state=seed)
ktrain=[]
ktest=[]
utrain=[]
des_splits=100
for slide_train_idx, slide_test_idx in splitter.split(slide_df.loc[:,'slide'],
                            slide_df.loc[:,'group'],                                         
                            groups=slide_df.loc[:,'slide']):
    if (np.sum(slide_df.loc[slide_train_idx,'class']==True) == k/2) \
        and (np.sum(slide_df.loc[slide_train_idx,'class']==False) == k/2):
        ktrain.append(slide_train_idx)
        ktest.append(slide_test_idx)
        utrain.append(str(np.sort(slide_train_idx)))
    if len(ktrain) == des_splits:
        break
print(len(ktrain),len(ktest),len(utrain))

100 100 100

In [118]:
# Understand GroupShuffleSplit uniquness across splits
seed=35
splitter = GroupShuffleSplit(n_splits=100, 
                             train_size=4,
                             random_state=seed)
keep=[]
# 
for slide_train_idx, slide_test_idx in splitter.split(slide_df.loc[:,'slide'],
                            slide_df.loc[:,'group'],                                         
                            groups=slide_df.loc[:,'slide']):
    sets=[slide_train_idx,slide_test_idx]
    keep.append(str(np.sort(slide_train_idx)))
    set_lab=['train','valid']
    df_list=[]
    n_train_test = [np.sum(slide_df.loc[slide_train_idx,'class']==True), #n pos
                    np.sum(slide_df.loc[slide_train_idx,'class']==False), #n neg
                    np.sum(slide_df.loc[slide_test_idx,'class']==True), #n pos
                    np.sum(slide_df.loc[slide_test_idx,'class']==False)] #n neg
    if (np.sum(slide_df.loc[slide_train_idx,'class']==True) == 0) \
        or (np.sum(slide_df.loc[slide_train_idx,'class']==False) == 0):
        print('Train slides n=%d pos, %d neg, Test slides n=%d pos, %d neg' % tuple(n_train_test))
    

print(len(np.unique(keep)))

Train slides n=0 pos, 4 neg, Test slides n=16 pos, 15 neg
Train slides n=0 pos, 4 neg, Test slides n=16 pos, 15 neg
Train slides n=0 pos, 4 neg, Test slides n=16 pos, 15 neg
Train slides n=0 pos, 4 neg, Test slides n=16 pos, 15 neg
Train slides n=0 pos, 4 neg, Test slides n=16 pos, 15 neg
Train slides n=0 pos, 4 neg, Test slides n=16 pos, 15 neg
Train slides n=0 pos, 4 neg, Test slides n=16 pos, 15 neg
Train slides n=0 pos, 4 neg, Test slides n=16 pos, 15 neg
Train slides n=4 pos, 0 neg, Test slides n=12 pos, 19 neg
Train slides n=0 pos, 4 neg, Test slides n=16 pos, 15 neg
Train slides n=0 pos, 4 neg, Test slides n=16 pos, 15 neg
100

In [85]:
# Create cross validation object
crossval_method = '5fold'
seed=42
n_repeats = 5
if 'fold' in crossval_method:
    k = int(crossval_method.split('f')[0])
    
if crossval_method == 'jackknife':        
    #Leave-one-out jack-knife    
    splitter=LeaveOneGroupOut()
elif crossval_method == '10fold':
    #Group 10kFold

    splitter = RepeatedKFold(n_splits=k, 
                             n_repeats=n_repeats,
                             random_state=seed)
elif crossval_method == '5fold':
    splitter = RepeatedKFold(n_splits=k, 
                             n_repeats=n_repeats,
                             random_state=seed)
    
balance_tiles_per_slide=[True, False]
ntarget=300
fold=0 #Initialize
all_test=[]
balance_classes_total_tiles=[True,False]
for slide_train_idx, slide_test_idx in splitter.split(slide_df.loc[:,'slide'],
                            slide_df.loc[:,'group'],                                         
                            groups=slide_df.loc[:,'slide']):
    print('\nFold %d' % fold)
    sets=[slide_train_idx,slide_test_idx]
    set_lab=['train','valid']
    df_list=[]
    n_train_test = [np.sum(slide_df.loc[slide_train_idx,'class']==True), #n pos
                    np.sum(slide_df.loc[slide_train_idx,'class']==False), #n neg
                    np.sum(slide_df.loc[slide_test_idx,'class']==True), #n pos
                    np.sum(slide_df.loc[slide_test_idx,'class']==False)] #n neg
    print('Train slides n=%d pos, %d neg, Test slides n=%d pos, %d neg' % tuple(n_train_test))
    for i,ds in enumerate(sets):   
        use_slides=list(slide_df.loc[ds,'slide'])

        #balance slides (?): i.e. only draw from equal numbers of top level data (slides)
        
        # Balance n tiles drawn per-slide:
        n=[]
        on=[]
        if balance_tiles_per_slide[i] == True:
            for ii,slide_id in enumerate(use_slides):
                keep = np.argwhere(np.array(all_dat.loc[:,'slide'].isin([slide_id]))).flatten()
                n0 = keep.shape[0]
                on.append(n0)
                if n0 > ntarget:
                    keep= resample(keep,
                          n_samples=ntarget,
                          random_state=fold,
                          replace = False,)
                if ii==0:
                    bal_dat = all_dat.loc[keep,('fn','slide','class')].reset_index(drop=True)
                else:
                    temp=all_dat.loc[keep,('fn','slide','class')].reset_index(drop=True)
                    bal_dat= pd.concat((bal_dat,temp),axis=0)
                    
                ntiles=keep.shape[0]
                n.append(ntiles)
            print('\t pre rebalance: median n tiles / svs %s = %4.1f' % (set_lab[i],np.median(on)))
            print('\t after rebalance: median n tiles / svs %s = %4.1f' % (set_lab[i],np.median(n)))
            bal_dat.reset_index(inplace=True,drop=True)
        else:
            #Initialize dataframe with all tiles from use_slides:
            use_tiles=all_dat.loc[:,'slide'].isin(use_slides) #Index of tiles from slide(s) in current set 'ds' (train / valid)
            bal_dat=pd.DataFrame(all_dat.loc[use_tiles,('fn','slide','class')]).reset_index(drop=True)
        
        # Balance final classes from tiles in bal_dat:
        if balance_classes_total_tiles[i] == True:
            #Resample tiles to have equal number of class examples following any previous balancing:  
            use_fn=bal_dat.loc[:,'fn']
            use_class=bal_dat.loc[:,'class']=='pos'
            npos=np.sum(use_class)
            nneg=len(use_class)-npos
            use_n = np.min([npos,nneg])
            print('Balancing %s tiles... %d neg %d pos, use %d' % (set_lab[i],nneg, npos,use_n))
            if npos > nneg:
                old_pos=np.argwhere(np.array(use_class)==True)
                neg=np.argwhere(np.array(use_class)==False)
                new=resample(old_pos,
                             replace=False,
                             n_samples=use_n,
                             random_state=fold)
                bal_tiles_idx=np.concatenate((neg,new))
            elif nneg > npos:
                old_neg=np.argwhere(np.array(use_class)==False)
                pos=np.argwhere(np.array(use_class)==True)
                new=resample(old_neg,
                             replace=False,
                             n_samples=use_n,
                             random_state=fold)
                bal_tiles_idx=np.concatenate((new,pos))
            temp=pd.DataFrame(bal_dat.loc[bal_tiles_idx[:,0],('fn','slide','class')]).reset_index(drop=True)
        else:
            use_class=bal_dat.loc[:,'class']=='pos'
            npos=np.sum(use_class)
            nneg=len(use_class)-npos
            print('Not balancing %s ... %d neg %d pos, use all.' % (set_lab[i],nneg, npos))
            temp=pd.DataFrame(bal_dat.loc[:,('fn','slide','class')]).reset_index(drop=True)
        temp['is_valid']=i
        if i == 0:
            out=temp
        else:
            out=pd.concat((out,temp),axis=0)
    print('n_pos =',
          np.sum(np.array(out.loc[out.loc[:,'is_valid']==0,'class'])=='pos'), 
          '(should ==) n_neg=', 
          np.sum(np.array(out.loc[out.loc[:,'is_valid']==0,'class'])=='neg')
         )    
    fold += 1

Fold 0
Train slides n=12 pos, 16 neg, Test slides n=4 pos, 3 neg
	 pre rebalance: median n tiles / svs train = 946.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4149 neg 3600 pos, use 3600
Not balancing valid ... 1580 neg 5963 pos, use all.
n_pos = 3600 (should ==) n_neg= 3600

Fold 1
Train slides n=13 pos, 15 neg, Test slides n=3 pos, 4 neg
	 pre rebalance: median n tiles / svs train = 1003.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4090 neg 3830 pos, use 3830
Not balancing valid ... 4339 neg 4745 pos, use all.
n_pos = 3830 (should ==) n_neg= 3830

Fold 2
Train slides n=13 pos, 15 neg, Test slides n=3 pos, 4 neg
	 pre rebalance: median n tiles / svs train = 790.5
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4088 neg 3830 pos, use 3830
Not balancing valid ... 3550 neg 14783 pos, use all.
n_pos = 3830 (should ==) n_neg= 3830

Fold 3
Train slides n=13 pos, 15 neg, Test slides n=3 pos, 4 neg
	 pre rebalance: median n tiles / svs train = 939.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3933 neg 3830 pos, use 3830
Not balancing valid ... 3025 neg 5203 pos, use all.
n_pos = 3830 (should ==) n_neg= 3830

Fold 4
Train slides n=13 pos, 15 neg, Test slides n=3 pos, 4 neg
	 pre rebalance: median n tiles / svs train = 773.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3820 neg 3830 pos, use 3820
Not balancing valid ... 4537 neg 4088 pos, use all.
n_pos = 3820 (should ==) n_neg= 3820

Fold 5
Train slides n=13 pos, 15 neg, Test slides n=3 pos, 4 neg
	 pre rebalance: median n tiles / svs train = 946.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4090 neg 3830 pos, use 3830
Not balancing valid ... 1891 neg 3534 pos, use all.
n_pos = 3830 (should ==) n_neg= 3830

Fold 6
Train slides n=12 pos, 16 neg, Test slides n=4 pos, 3 neg
	 pre rebalance: median n tiles / svs train = 1003.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4501 neg 3530 pos, use 3530
Not balancing valid ... 1034 neg 6458 pos, use all.
n_pos = 3530 (should ==) n_neg= 3530

Fold 7
Train slides n=12 pos, 16 neg, Test slides n=4 pos, 3 neg
	 pre rebalance: median n tiles / svs train = 790.5
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4120 neg 3530 pos, use 3530
Not balancing valid ... 4000 neg 17115 pos, use all.
n_pos = 3530 (should ==) n_neg= 3530

Fold 8
Train slides n=13 pos, 15 neg, Test slides n=3 pos, 4 neg
	 pre rebalance: median n tiles / svs train = 1074.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3849 neg 3900 pos, use 3849
Not balancing valid ... 2726 neg 2907 pos, use all.
n_pos = 3849 (should ==) n_neg= 3849

Fold 9
Train slides n=14 pos, 14 neg, Test slides n=2 pos, 5 neg
	 pre rebalance: median n tiles / svs train = 748.5
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3520 neg 4130 pos, use 3520
Not balancing valid ... 7380 neg 4768 pos, use all.
n_pos = 3520 (should ==) n_neg= 3520

Fold 10
Train slides n=14 pos, 14 neg, Test slides n=2 pos, 5 neg
	 pre rebalance: median n tiles / svs train = 939.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3788 neg 4130 pos, use 3788
Not balancing valid ... 4102 neg 1683 pos, use all.
n_pos = 3788 (should ==) n_neg= 3788

Fold 11
Train slides n=15 pos, 13 neg, Test slides n=1 pos, 6 neg
	 pre rebalance: median n tiles / svs train = 748.5
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3490 neg 4430 pos, use 3490
Not balancing valid ... 7432 neg 11736 pos, use all.
n_pos = 3490 (should ==) n_neg= 3490

Fold 12
Train slides n=11 pos, 17 neg, Test slides n=5 pos, 2 neg
	 pre rebalance: median n tiles / svs train = 848.5
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4449 neg 3230 pos, use 3230
Not balancing valid ... 2154 neg 9831 pos, use all.
n_pos = 3230 (should ==) n_neg= 3230

Fold 13
Train slides n=13 pos, 15 neg, Test slides n=3 pos, 4 neg
	 pre rebalance: median n tiles / svs train = 905.5
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3933 neg 3830 pos, use 3830
Not balancing valid ... 2420 neg 6378 pos, use all.
n_pos = 3830 (should ==) n_neg= 3830

Fold 14
Train slides n=11 pos, 17 neg, Test slides n=5 pos, 2 neg
	 pre rebalance: median n tiles / svs train = 1003.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4420 neg 3300 pos, use 3300
Not balancing valid ... 923 neg 5154 pos, use all.
n_pos = 3300 (should ==) n_neg= 3300

Fold 15
Train slides n=14 pos, 14 neg, Test slides n=2 pos, 5 neg
	 pre rebalance: median n tiles / svs train = 1003.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3817 neg 4130 pos, use 3817
Not balancing valid ... 3678 neg 1882 pos, use all.
n_pos = 3817 (should ==) n_neg= 3817

Fold 16
Train slides n=11 pos, 17 neg, Test slides n=5 pos, 2 neg
	 pre rebalance: median n tiles / svs train = 1081.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4690 neg 3300 pos, use 3300
Not balancing valid ... 761 neg 3492 pos, use all.
n_pos = 3300 (should ==) n_neg= 3300

Fold 17
Train slides n=11 pos, 17 neg, Test slides n=5 pos, 2 neg
	 pre rebalance: median n tiles / svs train = 722.5
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4420 neg 3230 pos, use 3230
Not balancing valid ... 2493 neg 12047 pos, use all.
n_pos = 3230 (should ==) n_neg= 3230

Fold 18
Train slides n=15 pos, 13 neg, Test slides n=1 pos, 6 neg
	 pre rebalance: median n tiles / svs train = 1003.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3333 neg 4430 pos, use 3333
Not balancing valid ... 6765 neg 528 pos, use all.
n_pos = 3333 (should ==) n_neg= 3333

Fold 19
Train slides n=13 pos, 15 neg, Test slides n=3 pos, 4 neg
	 pre rebalance: median n tiles / svs train = 790.5
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3820 neg 3830 pos, use 3820
Not balancing valid ... 3334 neg 16833 pos, use all.
n_pos = 3820 (should ==) n_neg= 3820

Fold 20
Train slides n=14 pos, 14 neg, Test slides n=2 pos, 5 neg
	 pre rebalance: median n tiles / svs train = 1003.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3819 neg 4130 pos, use 3819
Not balancing valid ... 3530 neg 3896 pos, use all.
n_pos = 3819 (should ==) n_neg= 3819

Fold 21
Train slides n=12 pos, 16 neg, Test slides n=4 pos, 3 neg
	 pre rebalance: median n tiles / svs train = 912.5
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4120 neg 3600 pos, use 3600
Not balancing valid ... 3375 neg 2883 pos, use all.
n_pos = 3600 (should ==) n_neg= 3600

Fold 22
Train slides n=12 pos, 16 neg, Test slides n=4 pos, 3 neg
	 pre rebalance: median n tiles / svs train = 939.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4388 neg 3530 pos, use 3530
Not balancing valid ... 1059 neg 17392 pos, use all.
n_pos = 3530 (should ==) n_neg= 3530

Fold 23
Train slides n=12 pos, 16 neg, Test slides n=4 pos, 3 neg
	 pre rebalance: median n tiles / svs train = 722.5
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 4120 neg 3530 pos, use 3530
Not balancing valid ... 4045 neg 7776 pos, use all.
n_pos = 3530 (should ==) n_neg= 3530

Fold 24
Train slides n=14 pos, 14 neg, Test slides n=2 pos, 5 neg
	 pre rebalance: median n tiles / svs train = 1003.0
	 after rebalance: median n tiles / svs train = 300.0
Balancing train tiles... 3633 neg 4130 pos, use 3633
Not balancing valid ... 5022 neg 2835 pos, use all.
n_pos = 3633 (should ==) n_neg= 3633

In [82]:
print(len(bal_tiles_idx),bal_dat.shape[0], len(np.unique(bal_tiles_idx)),max(bal_tiles_idx[:,0]))
print(np.sum(out.loc[:,'is_valid']),out.shape[0])
print('n_pos',np.sum(np.array(out.loc[out.loc[:,'is_valid']==False,'class'])=='pos'), 'should == n_neg', 
     np.sum(np.array(out.loc[out.loc[:,'is_valid']==False,'class'])=='neg'),)

7266 7857 7266 7762
7857 15123
n_pos 3633 should == n_neg 3633

In [52]:
fold = 0
csv_path=Path('~/data/biliseq_proc/v6/tiles_model/resnet18_jackknife_v0/csv')
df=pd.read_csv(csv_path.joinpath('train_valid_fold_%d.csv' % fold))
tissue =DataBlock(blocks=(ImageBlock, CategoryBlock),
                  get_x=ColReader('full_path'),
                  splitter=ColSplitter('is_valid') ,# GrandparentSplitter(train_name='train',valid_name='valid'),
                  get_y=  ColReader('class'), #using_attr(RegexLabeller(re_class), 'name'),
                  item_tfms=Resize(460) if use == 'summary' else None,
                  batch_tfms=aug_transforms(size=224,
                                            max_rotate=45,
                                            min_scale=0.75,
                                            flip_vert=True,
                                           )
                             ) 
dls = tissue.dataloaders(df, bs = 128)
learn = cnn_learner(dls, eval('resnet34'),
                metrics=[error_rate, accuracy],
                ).to_fp16()

/ihome/rbao/bri8/envs/fastai/lib/python3.8/site-packages/torch/_tensor.py:1023: UserWarning: torch.solve is deprecated in favor of torch.linalg.solveand will be removed in a future PyTorch release.
torch.linalg.solve has its arguments reversed and does not return the LU factorization.
To get the LU factorization see torch.lu, which can be used with torch.lu_solve or torch.lu_unpack.
X = torch.solve(B, A).solution
should be replaced with
X = torch.linalg.solve(A, B) (Triggered internally at  /opt/conda/conda-bld/pytorch_1631630839582/work/aten/src/ATen/native/BatchLinearAlgebra.cpp:760.)
  ret = func(*args, **kwargs)

In [16]:
for fold in range(0,1):
    print('Fold :', fold )
    df=pd.read_csv(csv_path.joinpath('train_valid_fold_%d.csv' % fold))
    tissue =DataBlock(blocks=(ImageBlock, CategoryBlock),
                      get_x=ColReader('full_path'),
                      splitter=ColSplitter('is_valid') ,# GrandparentSplitter(train_name='train',valid_name='valid'),
                      get_y=  ColReader('class'), #using_attr(RegexLabeller(re_class), 'name'),
                      item_tfms=Resize(460) if use == 'summary' else None,
                      batch_tfms=aug_transforms(size=224,
                                                max_rotate=45,
                                                min_scale=0.75,
                                                flip_vert=True,
                                               )
                                 ) 
    dls = tissue.dataloaders(df, bs = 128)
    learn = cnn_learner(dls, resnet34,
                    metrics=[error_rate, accuracy],
                    ).to_fp16()

    learn.fine_tune(5,freeze_epochs=1)
    learn.export(fname=export_path.joinpath('resnet18_1_5_%d.pkl' % fold))
    print('Performing inference.')
    #Infer:
    pred=learn.get_preds(with_decoded=True)

Fold : 0

Performing inference.

In [10]:
pred=learn.get_preds(with_decoded=True)

In [17]:
print(pred[1][0:10], pred[2][0:10])
correct = np.array(pred[1]) == np.array(pred[2])
print(np.sum(correct)/len(correct))

TensorCategory([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) tensor([1, 1, 1, 0, 1, 1, 0, 1, 0, 1])
0.3803680981595092

In [46]:
df=pd.read_csv(csv_path.joinpath('train_valid_fold_%d.csv' % 0))

In [54]:
test_df=df.loc[df.is_valid==True,('slide','class')].reset_index(drop=True)
slides_c= ['%s_%s' slide,c for slide,c in test_df]
# u_slides_c=np.unique(slides_c)
# temp = [item.split('_') for item in u_slides_c]
# fold_df=pd.DataFrame(temp,columns=['slide','class'])
fold_df=pd.DataFrame((test_df))
test_slides=np.unique(test_df.loc[:,'slide'])
p=np.array(pred[0]) # Probability ['neg','pos'] (Can check with dls.vocab )
c=np.array(pred[2]) #Predictions decoded
fold_df['p1_fold_%d' % fold] = np.zeros((fold_df.shape[0],1))*np.nan
fold_df['wta_fold_%d' % fold] = np.zeros((fold_df.shape[0],1))*np.nan

for slide in test_slides:
    src_idx = np.array(test_df.loc[:,'slide']) == slide
    p1 = np.mean(p[src_idx,1])
    if np.sum(c[src_idx]==0) > np.sum(c[src_idx]==1):
        wta=0
    else:
        wta=1
    dest_idx = np.array(fold_df.loc[:,'slide'])== str(slide)
    # print(dest_idx,p1)
    fold_df.loc[dest_idx,'p1_fold_%d' % fold] = p1
    fold_df.loc[dest_idx,'wta_fold_%d' % fold] = wta
fold_df.head()

<ipython-input-54-7420389bdeb0>:19: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  dest_idx = np.array(fold_df.loc[:,'slide'])== str(slide)

KeyError: 'cannot use a single bool to index into setitem'

ValueError: too many values to unpack (expected 3)